version: '3'

services:
  postgres:
      image: postgres:latest
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER: aya
        POSTGRES_PASSWORD: aya
        POSTGRES_DB: ecommerce
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

  product:
      build:
        context: .
        dockerfile: product/dockerfile
      ports:
        - 3000:3000
      environment:
        - PGUSER=aya
        - PGHOST=postgres
        - PGDATABASE=ecommerce
        - PGPASSWORD=aya
        - PGPORT=5432
      depends_on:
        - postgres

  transaction:
      build:
        context: .
        dockerfile: transaction/dockerfile
      ports:
        - 4000:4000
      environment:
        - PGUSER=aya
        - PGHOST=postgres
        - PGDATABASE=ecommerce
        - PGPASSWORD=aya
        - PGPORT=5432
      depends_on:
        - postgres

