CREATE TABLE IF NOT EXISTS products (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255),
  sku VARCHAR(50),
  image VARCHAR(255),
  price INTEGER,
  description TEXT
);


CREATE TABLE IF NOT EXISTS adjustment_transaction (
  id SERIAL PRIMARY KEY,
  SKU VARCHAR(255) NOT NULL UNIQUE,
  Qty INTEGER NOT NULL,
  Amount DECIMAL(10, 2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (SKU) REFERENCES products (SKU) ON DELETE CASCADE
);
